2.TEMP에서 박문수보다  급여를 적게받는 직원 검색 (셀프조인)

SELECT T1.EMP_ID, T1.EMP_NAME, T1.SALARY
FROM TEMP T1, TEMP T2
WHERE T1.SALARY < T2.SALARY AND
T2.EMP_NAME = '박문수'
;
3.EMP_LEVEL 에서 급여 산술평균을 구하고 TEMP 사원 중 자기 직급의 
    산술평균 보다 급여가 작은 직원 가져오기

SELECT (T1.TO_SAL + T1.FROM_SAL)/2,T2.EMP_ID,T2.EMP_NAME
FROM EMP_LEVEL T1, TEMP T2
WHERE T1.LEV = T2.LEV
AND(T1.TO_SAL + T1.FROM_SAL)/2 < T2.SALARY;


4.TEMP ,TCOM을 EMP_ID로 연결하여 모든 정보를 가져오되,  TEMP에 존재하는 자료 기준 모두

SELECT * FROM TEMP T1, TCOM T2
WHERE T1.EMP_ID = T2.EMP_ID(+)
AND T2.WORK_YEAR(+)<'2020'; // (+)가 들어가는 테이블에서 컬럼을 가져올 경우 그 조건에도 모두 (+)붙여야 한다.





5.EMP_ID 마다 자신보다 SALARY가 높은 인원 COUNT

SELECT T1.EMP_NAME, COUNT(T2.EMP_ID) AS 많은_수
FROM TEMP T1
LEFT OUTER JOIN TEMP T2
ON T1.SALARY < T2.SALARY
GROUP BY T1.EMP_NAME;



6.  TEMP 와 TDEPT CROSS JOIN
SELECT 
    * FROM TEMP
    CROSS JOIN TDEPT;


7.  TEMP 와 TDEPT NATURAL JOIN
SELECT 
    * FROM TEMP
    NATURAL JOIN TDEPT;

SELECT EMP_ID, DEPT

9.  NATURAL JOIN ON 을 사용하여 사원,부서,EMP_LEV 정보 조인

SELECT T1.EMP_NAME, T1.DEPT_CODE,
       T2.LEV
FROM TEMP T1 
JOIN EMP_LEVEL T2
ON T1.LEV = T2.LEV;


10.  사번, 성명, TEMP.부서코드, TDEPT.부서코드 , 부서명을 가져오는 LEFT OUTER JOIN 수행

SELECT T1.EMP_ID, T1.EMP_NAME, T1.DEPT_CODE,
       T2.DEPT_NAME,T2.DEPT_CODE
FROM TEMP T1 
LEFT OUTER JOIN TDEPT T2
ON T1.DEPT_CODE = T2.DEPT_CODE;


11.  10번을 FROM절에 오는 테이블과 outer JOIN절에 오는 테이블만 바꿔서 수행



12.  사번, 성명, TEMP.부서코드, TDEPT.부서코드 , 부서명을 가져오는 RIGHT OUTER JOIN 수행

	SELECT T1.EMP_ID, T1.EMP_NAME, T1.DEPT_CODE,
       T2.DEPT_NAME,T2.DEPT_CODE
FROM TEMP T1 
RIGHT OUTER JOIN TDEPT T2
ON T1.DEPT_CODE = T2.DEPT_CODE;

13. 사번, 성명, TEMP.부서코드, TDEPT.부서코드 , 부서명을 가져오는 FULL OUTER JOIN 수행

SELECT T1.EMP_ID, T1.EMP_NAME, T1.DEPT_CODE,
       T2.DEPT_NAME,T2.DEPT_CODE
FROM TEMP T1 
FULL OUTER JOIN TDEPT T2
ON T1.DEPT_CODE = T2.DEPT_CODE;

14. 13번에서 사번이 2020로 시작하는 직원만 검색

SELECT T1.EMP_ID, T1.EMP_NAME, T1.DEPT_CODE,
       T2.DEPT_NAME,T2.DEPT_CODE
FROM TEMP T1 JOIN TDEPT T2
ON (T1.DEPT_CODE = T2.DEPT_CODE)
AND T1.EMP_ID LIKE '2000%';;

//


15.사원테이블의 SALARY를 홀.짝수 달  1:2의 비율로 나누어 지급하는데 커미션 테이블에 커미션이 등록된 사원은 해당 커미션을 매월 급여에 더해 지급하고자 합니다.
    별도의 테이블을 만들어 직원 수 만큼의  ROW를 생성하고 1월부터 12월까지 지급 금액을 컬럼으로 관리할 수 있도록 하세요. (T2_DATA 구조 : EMP_ID, SAL01, SAL02,….,SAL12)
    단, SALARY를 나눈 급여의 소수점 아래는 원 단위로 올림 처리 합니다.’’’

CREATE TABLE T2_DATA
AS
SELECT A.EMP_ID,
    CEIL(SALARY/18) + NVL(COMM,0) SAL01,
    CEIL(SALARY/9)  + NVL(COMM,0) SAL02,
    CEIL(SALARY/18) + NVL(COMM,0) SAL03,
    CEIL(SALARY/9)  + NVL(COMM,0) SAL04,
    CEIL(SALARY/18) + NVL(COMM,0) SAL05,
    CEIL(SALARY/9)  + NVL(COMM,0) SAL06,
    CEIL(SALARY/18) + NVL(COMM,0) SAL07,
    CEIL(SALARY/9)  + NVL(COMM,0) SAL08,
    CEIL(SALARY/18) + NVL(COMM,0) SAL09,
    CEIL(SALARY/9)  + NVL(COMM,0) SAL10,
    CEIL(SALARY/18) + NVL(COMM,0) SAL11,
    CEIL(SALARY/9)  + NVL(COMM,0) SAL12
FROM TEMP A, TCOM B
WHERE B.EMP_ID(+) = A.EMP_ID
AND B.WORK_YEAR(+) = '2020'
ORDER BY 1;





