CREATE TABLE test_tab2(
             id     NUMBER(2),
             name   VARCHAR2(10),
             CONSTRAINT id_pk PRIMARY KEY(id) );
        
CREATE TABLE EMP_TAB(
    EMPNO   NUMBER(4),
    ENAME   VARCHAR2(10),
    DEPTNO  VARCHAR2(6) NOT NULL,
    CONSTRAINT EMP_DEPTNO_FK FOREIGN KEY (DEPTNO)
    REFERENCES TDEPT(DEPT_CODE));
             
DESC TDEPT;

CREATE TABLE UNI_TAB2 (
    DEPTNO  NUMBER(2),
    DNAME   CHAR(14),
    CONSTRAINT UNI_TAB_DEPTNO_UK UNIQUE (DEPTNO));
    
CREATE TABLE NN_TAB1 (
    DEPTNO  NUMBER(2) NOT NULL,
    DNAME   CHAR(14),
    IOC CHAR(13));
    
CREATE TABLE CK_TAB2 (
    DEPTNO  NUMBER(2),
    DNAME   CHAR(14),
    IOC     CHAR(13),
    CONSTRAINT UNI_TAB_DEPTNO_CK CHECK
    (DEPTNO IN (10,20,30,40,50)));
    
    
SELECT * FROM CK_TAB2;

INSERT INTO CK_TAB2 (DEPTNO)
        VALUES(10);
        
ALTER TABLE CK_TAB2
ADD CONSTRAINT EMP_ENAME_UK UNIQUE (DNAME);

ALTER TABLE CK_TAB2
DROP CONSTRAINT EMP_ENAME_UK;

SELECT * FROM ALL_CONSTRAINTS
WHERE TABLE_NAME = 'CK_TAB2';

ROLLBACK;

ALTER TABLE CK_TAB2
DISABLE CONSTRAINT UNI_TAB_DEPTNO_CK;

ALTER TABLE CK_TAB2
ENABLE CONSTRAINT UNI_TAB_DEPTNO_CK;

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'TEMP';

SELECT CONSTRAINT_NAME, COLUMN_NAME
FROM USER_CONS_COLUMNS
WHERE TABLE_NAME = 'TEMP';

CREATE TABLE POST(
            POST1   CHAR(3),
            POST2   CHAR(3),
            ADDR    VARCHAR2(60)    CONSTRAINT POST_ADDR_NN NOT NULL,
            CONSTRAINT POST_POST12_PK PRIMARY KEY(POST1,POST2));
            
            
CREATE TABLE EMP_30
    AS SELECT EMP_ID, TEL, SALARY
    FROM TEMP
    WHERE DEPT_CODE = 'BC0001';
    
ALTER TABLE BONUS
ADD     (ETC VARCHAR2(50));
ROLLBACK;

ALTER TABLE TEMP
MODIFY (EVAL_YN VARCHAR2(50));



DESC TEMP;